AWSTemplateFormatVersion: "2010-09-09"
Description: A code commit template

Parameters:
  PasswordTemp1:
    NoEcho: 'true'
    Type: String
    Description: New account password
    MinLength: '1'
    MaxLength: '41'
    ConstraintDescription: the password must be between 1 and 41 characters
  
  PasswordTemp2:
    NoEcho: 'true'
    Type: String
    Description: New account password
    MinLength: '1'
    MaxLength: '41'
    ConstraintDescription: the password must be between 1 and 41 characters


Resources:
  muneebDev:
    Type: AWS::IAM::Group
  muneebSDev:
    Type: AWS::IAM::Group
    
  muneebTemp1:
    Type: AWS::IAM::User
    Properties:
      LoginProfile:
        Password: !Ref 'PasswordTemp1'
  muneebTemp2:
    Type: AWS::IAM::User
    Properties:
      LoginProfile:
        Password: !Ref 'PasswordTemp2'

  Users:
    Type: AWS::IAM::UserToGroupAddition
    Properties:
      GroupName: !Ref 'muneebDev'
      Users: [!Ref 'muneebTemp1']
  
  SDevUsers:
    Type: AWS::IAM::UserToGroupAddition
    Properties:
      GroupName: !Ref 'muneebSDev'
      Users: [!Ref 'muneebTemp2']

  MuneebCodeCommit:
    Type: AWS::CodeCommit::Repository
    Properties:
     RepositoryName: "MuneebRepository"
     RepositoryDescription: "A great Repo"
     Code:
      S3:
       Bucket: "muneeb-bucket1"
       Key: "code.zip"
    

  DevPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: "DevPolicy"
      PolicyDocument:
        Statement:
        - Effect: Allow
          Action: "*"
          Resource: !GetAtt MuneebCodeCommit.Arn
        - Effect: Deny
          Action: [
            'codecommit:GitPush',
            'codecommit:DeleteBranch',
            'codecommit:PutFile',
            'codecommit:Merge*'
            ]
          Resource: !GetAtt MuneebCodeCommit.Arn
          Condition:
           StringEqualsIfExists:
            codecommit:References:
            - refs/heads/master
            - refs/heads/prod
            - refs/heads/Stg
            - refs/heads/develop
           'Null':
              codecommit:References: false

      Groups: [!Ref 'muneebDev']
    
  SDevPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: "SDevPolicy"
      PolicyDocument:
        Statement:
        - Effect: Allow
          Action: [
            'codecommit:Get*',
            'codecommit:GitPush',
            'codecommit:GitPull',
            'codecommit:DeleteBranch',
            'codecommit:PutFile',
            'codecommit:Merge*'
            ]
          Resource: !GetAtt MuneebCodeCommit.Arn
      Groups: [!Ref 'muneebSDev']

  CFNKeysTemp1:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref 'muneebTemp1'
  CFNKeysTemp2:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref 'muneebTemp2'
      
Outputs:
  AccessKeyTemp1:
    Value: !Ref 'CFNKeysTemp1'
    Description: AWSAccessKeyId of new user
  SecretKey1:
    Value: !GetAtt [CFNKeysTemp1, SecretAccessKey]
    Description: AWSSecretAccessKey of new user
  
  AccessKeyTemp2:
    Value: !Ref 'CFNKeysTemp2'
    Description: AWSAccessKeyId of new user
  SecretKey2:
    Value: !GetAtt [CFNKeysTemp2, SecretAccessKey]
    Description: AWSSecretAccessKey of new user