Parameters:
  
  RepositoryName:
    Description: CodeComit-Repository-Name
    Type: String
    Default: muneeb-repo
  BranchName:
    Description: CodeCommit-Branch-Name
    Type: String
    Default: master

Resources:
  AppPipeline:
    Type: 'AWS::CodePipeline::Pipeline'
    Properties:
      Name: muneeb-pipline-task2
      RoleArn: "arn:aws:iam::692560313237:role/service-role/AWSCodePipelineServiceRole-us-east-1-muneeb-pipeline-task1"
      Stages:
        - Name: Source
          Actions:
            - Name: CodeCommit
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: 1
                Provider: CodeCommit
              OutputArtifacts:
                - Name: SourceFiles
              Configuration:
                BranchName: !Ref BranchName
                RepositoryName: !Ref RepositoryName
                PollForSourceChanges: false
              RunOrder: 1

        - Name: CodeBuild
          Actions:
            - Name: Build
              InputArtifacts:
                - Name: SourceFiles
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              OutputArtifacts:
                - Name: PackagedFile
              Configuration:
                ProjectName: !Ref MuneebCodeBuildProject
              RunOrder: 1

        - Name: Deploy
          Actions:
            - Name: Deploy
              InputArtifacts:
                - Name: PackagedFile
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              Configuration:
                ActionMode: CREATE_UPDATE
                RoleArn: "arn:aws:iam::692560313237:role/shaheryar-cloudformation-role"
                StackName: muneeb-stack-4
                Capabilities: CAPABILITY_IAM
                TemplateConfiguration: PackagedFile::config.json
                TemplatePath: PackagedFile::packaged-template.yml
              RunOrder: 1

      ArtifactStore:
         Type: S3
         Location: muneeb-output-bucket 


  MuneebCodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: MuneebCodeBuildProject
      ServiceRole: "arn:aws:iam::692560313237:role/service-role/codebuild-muneeb-codebuild-service-role"
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:1.0
      Source:
        Type: CODEPIPELINE
      TimeoutInMinutes: 10